### ISSUE TITLE
This appears to be an old duplicate overridden just below.

### ISSUE THREAD

**Issue by juestr** [renepickhardt/pickhardtpayments#11]
https://github.com/renepickhardt/pickhardtpayments/blob/39c5ae16ed54b8b94ad5aa517e8c894762dbb7a2/pickhardtpayments/UncertaintyChannel.py#L34

**Comment by renepickhardt** [comment]
Thank for the issue. But I am not sure it is. I have two constructors. One from a json blob and the other one from an existing channel. It might be that I don't use one of those right now (which could be the reason to delete it) but I don't think it's and old duplicate

**Comment by juestr** [comment]
You can't overload by type unless there's invisible dark magic involved? The second `__init__` just replaces the first.

**Comment by renepickhardt** [comment]
True that! C.f. https://stackoverflow.com/questions/25343981/method-overloading-for-different-argument-type-in-python will fix this thanks!
